// ⚙️ GENERATED BY TRISHUL — DO NOT EDIT

import { Router } from 'express';
import * as productController from './product.controller.js';
import { verifyToken } from '../middleware/auth/verifyToken.js';
import { requireRole } from '../middleware/auth/requireRole.js';
import { validate } from './product.validator.js';

const router = Router();

router.get('/products', validate('listProducts'), productController.listProducts);
router.post('/products', verifyToken, requireRole("admin"), validate('createProduct'), productController.createProduct);
router.put('/products/:id', verifyToken, requireRole("admin"), validate('updateProduct'), productController.updateProduct);
router.delete('/products/:id', verifyToken, requireRole("admin"), validate('deleteProduct'), productController.deleteProduct);

export default router;
