// ⚙️ GENERATED BY TRISHUL — DO NOT EDIT

import { env } from '../config/env.js';

/**
 * API Key verification middleware.
 * Checks x-api-key header against API_KEY from env.
 */
export function apiKeyCheck(req, res, next) {
  const apiKey = req.headers['x-api-key'];

  if (!apiKey) {
    return res.status(401).json({
      error: 'API key required.',
      message: 'Include an x-api-key header in your request.',
    });
  }

  if (apiKey !== env.API_KEY) {
    return res.status(401).json({
      error: 'Invalid API key.',
    });
  }

  next();
}
