// ⚙️ GENERATED BY TRISHUL — DO NOT EDIT

/**
 * Role guard middleware factory.
 * Returns middleware that checks req.user.role against required role.
 *
 * @param {string} role — required role (e.g. "admin", "user")
 * @returns {Function} — Express middleware
 */
export function requireRole(role) {
  return (req, res, next) => {
    if (!req.user) {
      return res.status(401).json({
        error: 'Authentication required before role check.',
      });
    }

    // TODO: Customize role hierarchy logic here
    // e.g., admin might have access to "user" routes too

    if (req.user.role !== role) {
      return res.status(403).json({
        error: `Access denied. Required role: ${role}.`,
        message: `Your role "${req.user.role || 'none'}" does not have sufficient permissions.`,
      });
    }

    next();
  };
}
