// ⚙️ GENERATED BY TRISHUL — DO NOT EDIT

import jwt from 'jsonwebtoken';
import { env } from '../config/env.js';

/**
 * JWT verification middleware.
 * Extracts Bearer token from Authorization header,
 * verifies it using JWT_SECRET, and attaches decoded
 * payload to req.user.
 */
export function verifyToken(req, res, next) {
  const authHeader = req.headers.authorization;

  if (!authHeader || !authHeader.startsWith('Bearer ')) {
    return res.status(401).json({
      error: 'Access denied. No token provided.',
      message: 'Include a Bearer token in the Authorization header.',
    });
  }

  const token = authHeader.split(' ')[1];

  try {
    const decoded = jwt.verify(token, env.JWT_SECRET);
    req.user = decoded;

    // TODO: Add any custom claims validation here
    // e.g., check if user is active, check token version, etc.

    next();
  } catch (error) {
    return res.status(401).json({
      error: 'Invalid or expired token.',
      message: error.message,
    });
  }
}
