import { generatePrismaModel } from './generatePrismaModel.js';

/**
 * Assembles a complete schema.prisma from all module definitions.
 * @param {Array} schema — array of module definitions
 * @returns {string} — complete schema.prisma content
 */
export function generatePrismaSchema(schema) {
    let prisma = `// ⚙️ GENERATED BY TRISHUL — DO NOT EDIT\n\n`;
    prisma += `generator client {\n`;
    prisma += `  provider = "prisma-client-js"\n`;
    prisma += `}\n\n`;
    prisma += `datasource db {\n`;
    prisma += `  provider = "postgresql"\n`;
    prisma += `  url      = env("DATABASE_URL")\n`;
    prisma += `}\n\n`;

    for (const moduleDef of schema) {
        const model = generatePrismaModel(moduleDef);
        if (model) {
            prisma += model + '\n';
        }
    }

    return prisma;
}
