// ⚙️ GENERATED BY TRISHUL — DO NOT EDIT

import { Router } from 'express';
import * as userController from './user.controller.js';
import { verifyToken } from '../middleware/auth/verifyToken.js';
import { requireRole } from '../middleware/auth/requireRole.js';
import { validate } from './user.validator.js';

const router = Router();

router.post('/users/register', validate('registerUser'), userController.registerUser);
router.post('/users/login', validate('loginUser'), userController.loginUser);
router.get('/users/:id/profile', verifyToken, validate('getProfile'), userController.getProfile);
router.put('/users/:id/profile', verifyToken, validate('updateProfile'), userController.updateProfile);
router.delete('/users/:id', verifyToken, requireRole("admin"), validate('deleteUser'), userController.deleteUser);

export default router;
