import fs from 'fs-extra';
import path from 'path';
import { logger } from './logger.js';

const GENERATED_HEADER = '// ⚙️ GENERATED BY TRISHUL — DO NOT EDIT\n\n';
const CANVAS_HEADER = '// ✍️ YOUR CANVAS — Write business logic here\n\n';

/**
 * Write a file with the appropriate Trishul header.
 * @param {string} filePath — absolute path to write
 * @param {string} content — file content (without header)
 * @param {object} options
 * @param {boolean} [options.isCanvas=false] — if true, uses the canvas header
 * @param {boolean} [options.dryRun=false] — if true, only logs
 * @param {boolean} [options.noHeader=false] — if true, no header is prepended
 */
export async function writeFile(filePath, content, options = {}) {
    const { isCanvas = false, dryRun = false, noHeader = false } = options;

    if (dryRun) {
        logger.dryRun(path.relative(process.cwd(), filePath));
        return;
    }

    let header = '';
    if (!noHeader) {
        header = isCanvas ? CANVAS_HEADER : GENERATED_HEADER;
    }

    await fs.ensureDir(path.dirname(filePath));
    await fs.writeFile(filePath, header + content, 'utf-8');
    logger.file(path.relative(process.cwd(), filePath));
}
