// ⚙️ GENERATED BY TRISHUL — DO NOT EDIT

import express from 'express';
import cors from 'cors';
import { errorHandler } from './middleware/error.middleware.js';

import userRoutes from './modules/user/user.routes.js';
import productRoutes from './modules/product/product.routes.js';

const app = express();

// Global middleware
app.use(cors());
app.use(express.json());
app.use(express.urlencoded({ extended: true }));

// Health check
app.get('/health', (req, res) => {
  res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// Mount module routes
app.use(userRoutes);
app.use(productRoutes);

// Global error handler (must be last)
app.use(errorHandler);

export default app;
